Repository nanoframework/nanoFramework.Hardware.Esp32, pull requests merged in 2019-07, with the labels that each got.

#70 Update pin mapping and fixes
  source/nanoFramework.Hardware.Esp32/Configuration.cs
  source/nanoFramework.Hardware.Esp32/DeviceTypePins.cs
  source/nanoFramework.Hardware.Esp32/GpioPins.cs
  source/nanoFramework.Hardware.Esp32/Properties/AssemblyInfo.cs
  source/nanoFramework.Hardware.Esp32/nanoFramework.Hardware.Esp32.nfproj
  source/nanoFramework.Hardware.Esp32/packages.config
Labels: Type: enhancement

#71 Update readme.txt
  source/readme.txt
Labels: Type: documentation

#73 Remove dependency from Windows.Devices.Gpio
  source/nanoFramework.Hardware.Esp32.DELIVERABLES.nuspec
  source/nanoFramework.Hardware.Esp32.nuspec
Labels: Type: dependencies
